version: '3'
services:
  www:
    env_file:
      - .env
    volumes:
      - ./:/opt/app/
    ports:
      - '80:80'
    build:
      context: .
    restart: always

  redis:
    image: redis:5-alpine
    container_name: cache
    expose:
      - 6379
